<?xml version="1.0" encoding="utf-8"?><Database Name="Countries" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDb;Initial Catalog=Countries;Integrated Security=True" SettingsObjectName="ado_dz_5.Properties.Settings" SettingsPropertyName="CountriesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Information" Member="Information">
    <Type Name="Information">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Capital" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NumberOfInhabitants" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Area" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Continent" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>